#ifndef BULLET_H
#define BULLET_H

#include "RigidRect.h"

// Bullet class: Generated by GameManager, interacts with Clock
class Bullet : public RigidRect
{
public:
	Bullet(const int id, const float width, const float height, const float centX, const float centY,
			const float moveDirX, const float movedirY, unsigned int red = 255, unsigned int green = 255, unsigned int blue = 255);

	void displaySelf();
	void collide(const eRigidBodyType type);

private:
	bool checkBorderCollision();

	void explode();
};

#endif // !BULLET_H

